name: Deb Build

on:
  push:
    branches: [ "main", "RELEASE_6" ]
  pull_request:
    branches: [ "main", "RELEASE_6" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependancies
      run: sudo apt-get install -y build-essential libsystemd-dev nasm autotools-dev autoconf libjemalloc-dev tcl tcl-dev uuid-dev libcurl4-openssl-dev libbz2-dev libzstd-dev liblz4-dev libsnappy-dev libssl-dev pbuilder debhelper
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: make
      run: make USE_SYSTEMD=yes
      
    - name: Build Packages
      run: cd ./pkg/deb/ && ./deb-buildsource.sh

    - name: Store Debian package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Debian binary package files
        path: './pkg/deb/deb_files_generated/*'
